name: Build clientlib-ktx Sample App

on:
  push:
    branches: [ main ]
    paths: [ 'android/**', '.github/**', 'examples/example-clientlib-ktx-app/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'android/**', '.github/**', 'examples/example-clientlib-ktx-app/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: examples/example-clientlib-ktx-app

    steps:
      # Setup
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Build
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle and run tests
        run: ./gradlew build
