name: Expo Smoke Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1" # Every Monday, 5am UTC
  release:
    types: [ published ]

jobs:
  build:
    name: ${{ matrix.example.name }} (${{ matrix.version }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        example:
          - name: App
            package_name: mobile-wallet-adapter-protocol
            suffix: app
          - name: Wallet
            package_name: mobile-wallet-adapter-walletlib
            suffix: wallet
        version: [ 52, 53, 54, latest]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
      
      - name: Set up pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true
          cache_dependency_path: 'js/pnpm-lock.yaml'
          package_json_file: 'js/package.json'

      - name: set up JDK 17
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: 'Build Project'
        working-directory: 'js/'
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: 'Setup Expo ${{ matrix.example.name }}'
        working-directory: 'js/'
        run: |
          if [ "${{ matrix.version }}" = "latest" ]; then
            npx -y create-expo-app expo-${{ matrix.version }}-${{ matrix.example.suffix }} --template blank
          else
            npx -y create-expo-app expo-${{ matrix.version }}-${{ matrix.example.suffix }} --template blank@sdk-${{ matrix.version }}
          fi

      - name: 'Install ${{ matrix.example.package_name }}'
        working-directory: 'js/'
        run: |
          cd expo-${{ matrix.version }}-${{ matrix.example.suffix }}
          npm install file:../packages/${{ matrix.example.package_name }}

      - name: 'Build Expo ${{ matrix.example.name }}'
        working-directory: 'js/'
        run: |
          cd expo-${{ matrix.version }}-${{ matrix.example.suffix }}
          npx expo prebuild --no-install
          cd android && ./gradlew assembleDebug --no-daemon --stacktrace
