name: React Native Smoke Test

on:
  push:
    branches: [ main ]
    paths: [ '.github/**', 'js/**' ]
  pull_request:
    branches: [ main ]
    paths: [ '.github/**', 'js/**' ]
  release:
    types: [ published ]

jobs:
  build:
    name: ${{ matrix.example.name }} (${{ matrix.version }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        example:
          - name: App
            package_name: mobile-wallet-adapter-protocol
            suffix: App
          - name: Wallet
            package_name: mobile-wallet-adapter-walletlib
            suffix: Wallet
        version: [ 74, 80, latest]

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
      
      - name: Set up pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true
          cache_dependency_path: 'js/pnpm-lock.yaml'
          package_json_file: 'js/package.json'

      - name: set up JDK 17
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: 'Build Project'
        working-directory: 'js/'
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: 'Setup React Native ${{ matrix.example.name }}'
        working-directory: 'js/'
        run: |
          if [ "${{ matrix.version }}" = "latest" ]; then
            npx @react-native-community/cli@latest init React${{ matrix.version }}${{ matrix.example.suffix }}
          else
            npx @react-native-community/cli@latest init React${{ matrix.version }}${{ matrix.example.suffix }} --version 0.${{ matrix.version }}.0
          fi

      - name: 'Install ${{ matrix.example.package_name }}'
        working-directory: 'js/'
        run: |
          cd React${{ matrix.version }}${{ matrix.example.suffix }}
          npm install file:../packages/${{ matrix.example.package_name }}

      - name: 'Build React Native ${{ matrix.example.name }}'
        working-directory: 'js/'
        run: |
          cd React${{ matrix.version }}${{ matrix.example.suffix }}/android
          ./gradlew assembleDebug --no-daemon --stacktrace
